// Mocks generated by Mockito 5.4.5 from annotations
// in date_split_app/test/features/auth/data/repositories/auth_remote_data_source_implementation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:date_split_app/features/auth/data/datasources/auth_local_data_source.dart'
    as _i6;
import 'package:date_split_app/features/auth/data/datasources/auth_remote_data_source.dart'
    as _i3;
import 'package:date_split_app/features/auth/data/models/user_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserModel_0 extends _i1.SmartFake implements _i2.UserModel {
  _FakeUserModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i3.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> signUp({
    required String? email,
    required String? password,
    required String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
              #displayName: displayName,
            }),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #password: password,
                  #displayName: displayName,
                }),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#signIn, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> updateUser({
    required String? avatar,
    required String? nickName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [], {
              #avatar: avatar,
              #nickName: nickName,
            }),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#updateUser, [], {
                  #avatar: avatar,
                  #nickName: nickName,
                }),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> resetPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [email]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#resetPassword, [email]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> deleteAccount(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, [uid]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#deleteAccount, [uid]),
              ),
            ),
          )
          as _i4.Future<String>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i6.AuthLocalDataSource {
  MockAuthLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserModel> getUser() =>
      (super.noSuchMethod(
            Invocation.method(#getUser, []),
            returnValue: _i4.Future<_i2.UserModel>.value(
              _FakeUserModel_0(this, Invocation.method(#getUser, [])),
            ),
          )
          as _i4.Future<_i2.UserModel>);
}
